# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Price < Formula
  desc ""
  homepage "https://github.com/ixxiv/price-action"
  version "0.1.5"

  on_macos do
    url "https://github.com/ixxiv/price-action/releases/download/v0.1.5/price_0.1.5_macOS-all.tar.gz"
    sha256 "0ad89322c6c3eaa6b78450e6c07f4a761cc1a717b1e473348811509dc76c1047"

    def install
      bin.install "price"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ixxiv/price-action/releases/download/v0.1.5/price_0.1.5_Linux-ARM64.tar.gz"
      sha256 "2ebe39e1b5d2d794a66b0a4c43d2eaa2660f1f77ac3a2d7befaa9394005c6947"

      def install
        bin.install "price"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ixxiv/price-action/releases/download/v0.1.5/price_0.1.5_Linux-64bit.tar.gz"
      sha256 "c624967ebd1131e207fd81d704e9dbf93a82e35a4f6840267bd4b217f68db934"

      def install
        bin.install "price"
      end
    end
  end
end
