# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Price < Formula
  desc ""
  homepage "https://github.com/rxxcc/price-action"
  version "0.1.7"

  on_macos do
    url "https://github.com/rxxcc/price-action/releases/download/v0.1.7/price_0.1.7_macOS-all.tar.gz"
    sha256 "550636837b95d3f2487690eb22e4e16089a25f9ced2efe4243e11056088b166c"

    def install
      bin.install "price"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rxxcc/price-action/releases/download/v0.1.7/price_0.1.7_Linux-64bit.tar.gz"
      sha256 "f52f6a773d78f9e7e6ff87c6f8f05a95fcb865a95f10c1d703103684ff5b3bdb"

      def install
        bin.install "price"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rxxcc/price-action/releases/download/v0.1.7/price_0.1.7_Linux-ARM64.tar.gz"
      sha256 "4b6d946b181df1a05ca167342421db395e92fe56a56dd660048b985f6f63f929"

      def install
        bin.install "price"
      end
    end
  end
end
